### ISSUE TITLE
Does not work with elements containing ng-if

### ISSUE THREAD

**Issue by 4141done** [mjt01/angular-feature-flags#13]
Hi, first of all thanks for the library.  It seems that it does not work properly if there is an ng-if applied to the directive as I think the parent scope is being lost when the element is being manually transcluded.  I'm poking around trying to find a fix but thought I'd put it up here as well.  I've created a plunkr demonstrating the issue:

http://plnkr.co/edit/86tfkXsE06rlNU0NwWcr

Not sure if this is even worth handling, but I lost a few hours on it so I thought I'd bring it up.

**Comment by mjt01** [comment]
Thanks for opening this. My initial thoughts relate to component design, in that `activity-feed` as a directive is a self contained component and that if there were no feed items that component should know how to handle that internally.

That said, you are the second person to raise this and the fact that people are losing time makes me think it's something worth fixing.

Its a priority clash between `ng-if` and `feature-flag` both having the same priority. I'll offset these and that will resolve your issue.

**Comment by mjt01** [comment]
Committed the fix. Tagged it up in version 0.0.5 for you. Should do the trick.

**Comment by 4141done** [comment]
Hey thank you so much for the quick response.  It never occurred to me that the problem might be with priority.  Also point taken about the wisdom of using ng-if in that way.  After you commented I ended up reworking the problem code.  That being said I'm sure you've saved someone with a legitimate reason to have it there some time.  Thanks!
