### ISSUE TITLE
Does not work with jqLite

### ISSUE THREAD

**Issue by goldcaddy77** [mjt01/angular-feature-flags#16]
This library doesn't work with jqLite because you use `element.after`.  You should note this dependency in Bower or use a jqLite safe method.

**Comment by mjt01** [comment]
Can you clarify what you mean here please. `element.after` is in angulars jqLite https://docs.angularjs.org/api/ng/function/angular.element

**Comment by icfantv** [comment]
I'm assuming this isn't an issue since the reporter never bothered to get back to you?

**Comment by mjt01** [comment]
Correct. Closing and thanks

**Comment by icfantv** [comment]
Cool.  And thank you.
