### ISSUE TITLE
Move .set() function to a provider so we can set it in a config block

### ISSUE THREAD

**Issue by jmeiss** [mjt01/angular-feature-flags#18]
Hi,

First of all, thank you for this module which is really useful.

To configure this module, we have to set the features array in a `run` block and not in a `config` block who is used for, following AngularJS doc: https://docs.angularjs.org/guide/module

It would be nice to move the `set()` function in a provider to be able to set it in a `config` block

Thanks a lot :)

**Comment by mjt01** [comment]
My apologies, I appear to have missed this issue being raised. If i'm honest i havent done a lot of angular recently, so while i have experience with providers, im not 100% sure on the repercussions of this and whether it would be a breaking change.

You're welcome to submit a pull request if you like? :)

**Comment by mjt01** [comment]
Will be resolved by https://github.com/mjt01/angular-feature-flags/pull/25

**Comment by mjt01** [comment]
Added in v1.1.0

Thanks to @philsch
