### ISSUE TITLE
Setting the flags dynamically with expressions

### ISSUE THREAD

**Issue by svalinnetlight** [mjt01/angular-feature-flags#26]
I'm having an issue where I'm trying to set the flags in an ng-repeat dynamically using expressions, like so:

`<div ng-repeat="item in items" feature-flag="{{item.flag}}">`

The problem here is that this doesn't work, feature-flag seems to check it  before angular has had a chance to interpolate the expression and just states "feature flag: {{item.flag}} is off". Is there a solution or workaround for this?

**Comment by mjt01** [comment]
Added in v1.1.0

Thanks to @philsch
