### ISSUE TITLE
Publish 1.0 to npm

### ISSUE THREAD

**Issue by mikehaas763** [mjt01/angular-feature-flags#28]
Hey folks,

Looks like this lib is at a 1.0 but only 0.1.0 is published to npm. Can you publish 1.0?

**Comment by mjt01** [comment]
Yeah sorry about that, the build wasnt run before publishing so it published v0.1.0. There are two pull requests about to merge in so will publish v1.1.0 shortly.

**Comment by mjt01** [comment]
v1.1.0 is now available

Thanks for your patience
