### ISSUE TITLE
bower install does not work properly

### ISSUE THREAD

**Issue by maxmarkus** [mjt01/angular-feature-flags#35]
Hello, 

Just wanted to try out this nice thing you created, but unfortunately a bower install ends up in an folder with only two files: 
README.md  bower.json

Seems you latest change has modified something? 
also the dist in this repository is empty and throws 404 (I think this should consist of some feature-flags.min.js and other files)

Best, Max

**Comment by reviling** [comment]
Seconding Max's comment.

Specifically, the dist directory was added to gitignore: https://github.com/mjt01/angular-feature-flags/commit/9010882d9d30503b790de48800fd96c8421589f4

**Comment by mjt01** [comment]
Sorry looks like i tagged after that change, thought it was the other way around. I was working on changing how things get packaged up, but i'll go back to the old way.

**Comment by nikrolls** [comment]
Maybe dist should be in `npmignore` instead of `gitignore`? Then it will probably work.

**Comment by mjt01** [comment]
Nah i was trying to avoid having people create prs that include the built artifacts and have them build as part of the versioning process. This is trivial when you dont have bower support.

For now reinstating the dist directory and i'll just build this with the versioning commits

**Comment by mjt01** [comment]
Fixed in https://github.com/mjt01/angular-feature-flags/tree/v1.2.2

**Comment by reviling** [comment]
Thanks!
