### ISSUE TITLE
Feature Request: Add flag key for element selection

### ISSUE THREAD

**Issue by rcollette** [mjt01/angular-feature-flags#41]
When writing protractor automation tests that need to execute on not-yet deployed features, it would be helpful to be able to select flags by their flag key as id on the element that looks like:
```
<div class="feature-flags-flag" ng-repeat="flag in flags">
```
So it would look like
```
<div id="theFlagKey" class="feature-flags-flag" ng-repeat="flag in flags">
```

**Comment by jxc876** [comment]
is this so the test can tell if the feature is activated or not ? Otherwise why not just put the id there yourself ?

**Comment by rcollette** [comment]
Actually, I just looked at the source and noticed that id's already exist.   We fell behind in versions because we had submitted a PR at one point and were pointing to a commit id until the PR and publish happened.  We just never updated.

Closing.
